version: '3.8'

services:
  mysql_db1:
    image: mysql:8
    container_name: mysql_db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeclub_main
    ports:
      - "3308:3306"
    volumes:
      - db1_data:/var/lib/mysql

  mysql_db2:
    image: mysql:8
    container_name: mysql_db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeclub_properties
    ports:
      - "3309:3306"
    volumes:
      - db2_data:/var/lib/mysql
  
  mysql_db3:
    image: mysql:8
    container_name: mysql_db3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeclub_users
    ports:
      - "3310:3306"
    volumes:
      - db3_data:/var/lib/mysql

volumes:
  db1_data:
  db2_data:
  db3_data: